In [2]:
import numpy as np
import torch
import tensorflow as tf
from copy import deepcopy


T1 = torch.tensor([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
T1 = T1.flatten()[:-6]

T1

2024-10-25 12:25:22.704801: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-10-25 12:25:32.881603: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-25 12:25:33.592631: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-25 12:25:33.967419: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-25 12:25:36.581618: I tensorflow/core/platform/cpu_feature_guar

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [3]:
T2 = torch.reshape(T1, (2, 3, 2, 2))
T2

tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]]],


        [[[12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]]])

In [4]:
n2 = np.array(T2)
n2.flatten()
T3 = T1
res = torch.sum(T2, 1)
res

tensor([[[12, 15],
         [18, 21]],

        [[48, 51],
         [54, 57]]])

In [5]:
boh= torch.sum(res, (1,2))
boh/2

tensor([ 33., 105.])

In [9]:
T2

tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]]],


        [[[12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]]])

In [10]:

res1 = torch.sum(T2, (2,3))
res1

tensor([[ 6, 22, 38],
        [54, 70, 86]])

In [11]:
res2 = torch.sum(res1, 1)
res2

tensor([ 66, 210])

In [12]:
res2/2

tensor([ 33., 105.])